name: demoSAST
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Rodando o Build
      run: echo Build deu bom !
      
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    needs: build
    steps:
    - name: Rodande Dev
      run: echo Dev deu bom !
    
  deploy-sast:
    runs-on: ubuntu-latest
    environment:
      name: sast
    needs: build
    steps:
    - name: Rodando o HoruSec
      run: |
            sudo apt-get install git -y
            git clone https://github.com/crypto-br/demoSAST.git
            cd demoSAST
            curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash
            horusec start -p"./"
      
      
  
    
